Repository diginamic-projet-final-gp4/projet_final_gcjf, pull requests merged in 2024-03, with the labels that each got.

#18 Nico branch
  api-back/pom.xml
  api-back/src/main/java/com/diginamic/apiback/WIKI.md
  api-back/src/main/java/com/diginamic/apiback/config/JwtProviderConfig.java
  api-back/src/main/java/com/diginamic/apiback/config/SecurityConfig.java
  api-back/src/main/java/com/diginamic/apiback/models/Jwt.java
  api-back/src/main/java/com/diginamic/apiback/models/User.java
  api-back/src/main/java/com/diginamic/apiback/repository/JwtRepository.java
  api-back/src/main/resources/application.properties
  frontend/.eslintrc.cjs
  frontend/index.html
  frontend/public/vite.svg
  frontend/src/App.jsx
  frontend/src/assets/react.svg
  frontend/src/components/Test/Test.css
  frontend/src/components/Test/Test.jsx
  frontend/src/main.jsx
  frontend/vite.config.js
Labels: documentation, nouveauté

#20 Nico branch
  .gitignore
  GitProcedure.md
  WIKI.md
Labels: bug, documentation

#21 Backend authentification (Service & Ropository)
  .conception/MCDMPD.drawio
  .gitignore
  api-back/src/main/java/com/diginamic/apiback/controllers/AuthController.java
  api-back/src/main/java/com/diginamic/apiback/repository/UserRepository.java
  api-back/src/main/java/com/diginamic/apiback/services/AuthService.java
  api-back/src/main/java/com/diginamic/apiback/services/AuthServiceImpl.java
  api-back/src/main/java/com/diginamic/apiback/services/TokenService.java
  api-back/src/main/java/com/diginamic/apiback/services/TokenServiceImpl.java
  api-back/src/main/java/dto/LoginRequest.java
Labels: nouveauté, update

#22 Création d'utilisateur
  README.md
  api-back/pom.xml
  api-back/src/main/java/com/diginamic/apiback/controllers/AuthController.java
  api-back/src/main/java/com/diginamic/apiback/dto/LoginRequest.java
  api-back/src/main/java/com/diginamic/apiback/dto/RegisterRequest.java
  api-back/src/main/java/com/diginamic/apiback/models/User.java
  api-back/src/main/java/com/diginamic/apiback/repository/JwtRepository.java
  api-back/src/main/java/com/diginamic/apiback/services/AuthService.java
  api-back/src/main/java/com/diginamic/apiback/services/AuthServiceImpl.java
  api-back/src/main/java/com/diginamic/apiback/services/TokenServiceImpl.java
Labels: nouveauté, update

#23 Update Auth back & Router Front
  api-back/src/main/java/com/diginamic/apiback/controllers/AuthController.java
  api-back/src/main/java/com/diginamic/apiback/repository/JwtRepository.java
  api-back/src/main/java/com/diginamic/apiback/services/AuthServiceImpl.java
  api-back/src/main/java/com/diginamic/apiback/services/TokenService.java
  api-back/src/main/java/com/diginamic/apiback/services/TokenServiceImpl.java
  frontend/src/App.jsx
  frontend/src/components/Body/Body.jsx
  frontend/src/components/Test/Test.jsx
  frontend/src/main.jsx
  frontend/src/pages/Login/Login.jsx
  frontend/src/pages/NotFound/NotFound.css
  frontend/src/pages/NotFound/NotFound.jsx
Labels: nouveauté, update

#49 little fix
  frontend/src/App.jsx
  frontend/src/model/utils/context/UserContext.jsx
Labels: bug

#51 Ajout de page
  frontend/src/App.css
  frontend/src/components/Body/Body.css
  frontend/src/components/Body/Body.jsx
  frontend/src/index.css
  frontend/src/pages/Absence/CreerAbs.css
  frontend/src/pages/Absence/CreerAbs.jsx
  frontend/src/pages/Absence/GestionAbs.jsx
  frontend/src/pages/Absence/ModifAbs.jsx
  frontend/src/pages/Administration/AdminPage.css
  frontend/src/pages/Administration/AdminPage.jsx
  frontend/src/pages/Administration/TraitementAbs.jsx
  frontend/src/pages/Profile/MonProfile.jsx
  frontend/src/pages/Rapport/HistogrammePage.jsx
  frontend/src/pages/Rapport/ListCollabActuel.jsx
  frontend/src/pages/Rapport/RapportGlobPage.jsx
Labels: nouveauté, update

#52 fix :mise en place des routes
  api-back/src/main/java/com/diginamic/apiback/controllers/AuthController.java
  api-back/src/main/java/com/diginamic/apiback/controllers/UserController.java
  api-back/src/main/java/com/diginamic/apiback/models/Absence.java
  api-back/src/main/java/com/diginamic/apiback/models/Jwt.java
  api-back/src/main/java/com/diginamic/apiback/models/Service.java
  api-back/src/main/java/com/diginamic/apiback/models/User.java
Labels: update

#56 Ajouter le calendrier
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Body/Body.jsx
  frontend/src/pages/Absence/GestionAbs.css
  frontend/src/pages/Absence/GestionAbs.jsx
  frontend/src/pages/Login/Login.css
Labels: nouveauté

#65 changeAbsencePage
  frontend/src/pages/Absence/GestionAbs.css
  frontend/src/pages/Absence/GestionAbs.jsx
Labels: update

#63 Add histogram
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/Rapport/HistogrammePage.css
  frontend/src/pages/Rapport/HistogrammePage.jsx
Labels: nouveauté
